sudo: false
dist: trusty
services:
    - docker

env:
    global:
        - TESTDATA_DIR="$HOME/.cache/testdata"
        - DOCKER_DIR="$HOME/.cache/docker"
        - secure: tLyIDfETpHCDRyEqF2ROM8ue+D+fl/IeOdFBY/Mov7zhAHpgBdQQJi+HQ1/RK+G7DDsnM/FIjvCcf4etphmBHK3xs8vDM1oPntYs+3iE2AbTcVGglHYoX1++H76xPt3eXyf1S0frgVg6qYCNmuP0chhDUkYXPydcKvq1ANjfTQU= # BUILD_TRIGGER_URL

cache:
    directories:
        - $TESTDATA_DIR
        - $DOCKER_DIR


install: true

script:
    - test -f "$DOCKER_DIR/image.tar" && sudo docker load -i "$DOCKER_DIR/image.tar" || true
    - docker build -t my_image .
    - docker save -o "$DOCKER_DIR/image.tar" $(docker history -q my_image | grep -v '<missing>')
    - mkdir -p "$TESTDATA_DIR"
    - curl -L https://github.com/scitran/testdata/archive/master.tar.gz | tar xz -C "$TESTDATA_DIR" --strip-components 1
    - ./docker/test.sh --testdata "$TESTDATA_DIR"

after_success:
    - if [ "$TRAVIS_TAG" ]; then
          ./docker/build-trigger.sh Tag "$TRAVIS_TAG" "$BUILD_TRIGGER_URL";
      fi
    - if [ "$TRAVIS_EVENT_TYPE" == "push" -a "$TRAVIS_BRANCH" == "master" ]; then
          ./docker/build-trigger.sh Branch "$TRAVIS_BRANCH" "$BUILD_TRIGGER_URL";
      fi
