sudo: false
language: python
python:
    - "2.7"

env:
    global:
        - DCMTK_VERSION="dcmtk-3.6.1_20150924"
        - DCMTK_DB_DIR="dcmtk_dicom_db"
        - TESTDATA_DIR="testdata-ci"
        - ORTHANC_VERSION="Orthanc-1.1.0"

cache:
    pip: true
    directories:
        - $DCMTK_VERSION
        - $DCMTK_DB_DIR
        - $TESTDATA_DIR
        - $ORTHANC_VERSION

addons:
    apt:
        packages:
            - uuid-dev

before_install:
    - ln -s bin $VIRTUAL_ENV/sbin

install:
    - pip install .
    - pip install -U -r requirements-dev.txt
    - ./test/install_deps.sh

script:
    - ./test/test.sh
    - ./test/lint.sh reaper

after_success:
    - ./docker/build-trigger.sh Tag "${TRAVIS_TAG}" "${BUILD_TRIGGER_URL}"
